### ISSUE TITLE
Assertion Failures in PharoJsTools-Playground 

### ISSUE THREAD

**Issue by Francodavy** [bouraqadi/PharoJS#10]
1.Obtain Pharo6.1-64 via https://pharojs.github.io/faq.html
    
2.install PharoJs on Pharo image with
    Gofer it smalltalkhubUser: 'noury'
    project: 'PharoJS';
    configurationOf: #PharoJS ;
    loadBleedingEdge.
    
3.Via Test Runner
4.Write PharoJS on the top left of the Test runner
5.Click on PharoJsTools-Playground
6.Click PjPlaygroundTest
7.Run selected

These are the three failures from the running of the PharoJsTools-Playground Test
[tests_Pharo6.0_PharoJsTools-Playground.txt](https://github.com/bouraqadi/PharoJS/files/1842485/tests_Pharo6.0_PharoJsTools-Playground.txt)

**Comment by bouraqadi** [comment]
PharoJS is currently developed for Pharo 5. All tests are green on Pharo 5 only.
