### ISSUE TITLE
[Pharo 5] Javascript Interpreter NOT available

### ISSUE THREAD

**Issue by qCazelles** [bouraqadi/PharoJS#11]
To reproduce this :
Exactly like here : https://github.com/bouraqadi/PharoJS/issues/5

Except I'm on Pharo 5.0 !

**Comment by bouraqadi** [comment]
Just released a new version of PharoJS. It works fine with Ubuntu 18. 
Give it a try please.

**Comment by qCazelles** [comment]
I just did by trying loadStable and loadBleedingEdge on two different images.
Doesn't change anything from yesterday.
Thanks.

**Comment by bouraqadi** [comment]
Which web browser are you using?
Did you try with a fresh image?

**Comment by qCazelles** [comment]
firefox. And yes I only try with clean images, I use pharo-launcher.

**Comment by bouraqadi** [comment]
I suggest to switch the discussion to Slack. Send a private message to @pharojs to receive an invitation.
