### ISSUE TITLE
'€' asJSON renders as:  "â¬".

### ISSUE THREAD

**Issue by bouraqadi** [bouraqadi/PharoJS#13]
_Issue reported by Ivo on the PharoJS slack_
`'€' asJSON` renders as: ` "â¬"`.
I think some unicode escapement is missing

**Comment by Ironirc** [comment]
I think a quick fix (if dependency on STON is an option) might be:

**WideString>>printJsOn: aStream**
   STON jsonWriter 
      on: aStream;
      asciiOnly: true;
      nextPut: self .

One test fails after this, but the test itself looks strange to me.
![image](https://user-images.githubusercontent.com/10418880/66427155-b268c680-ea13-11e9-9976-252b9fd55b00.png)

**Comment by dvmason** [comment]
I have a working fix, just trying to get it committed.

**Comment by dvmason** [comment]
Committed now.
