### ISSUE TITLE
Bridge tests fail

### ISSUE THREAD

**Issue by siemenbaader** [bouraqadi/PharoJS#2]
## To reproduce:

1. Obtain a clean Pharo 5.0 image from http://get.pharo.org/50
2. Load latest PharoJS: 

```smalltalk
Gofer it
	smalltalkhubUser: 'noury' project: 'PharoJS';
	configurationOf: #PharoJS ;
	loadBleedingEdge.
```
3. Open `Test Runner` 

4. Locate **PharoJSBridge-Tests**

5. Select all tests and click **Run Selected** 

The first tests run fine. Eventually the browser will not connect to PharoJS. Pharo will display information: **Websocket is NOT availbale**. Re-running failing tests raises **ZnUnknownHttpMethod**.

No errors in browser log.

With *Firefox* as default browser, the issue occurs towards the end of the test suite. With *Chrome*, it occurs after just a few tests, and immediately after a few runs. The exact point when the issue occurs seems to vary. So I think it is ressource-related. 

![screen shot 2017-02-08 at 11 08 28](https://cloud.githubusercontent.com/assets/829667/22736473/90e22a24-edfe-11e6-9e1c-08aded0cec8e.png)

**Comment by bouraqadi** [comment]
Fixed in the latest stable
