### ISSUE TITLE
PharoJS source fails to load in current Pharo 6.1

### ISSUE THREAD

**Issue by FunctionPoint** [bouraqadi/PharoJS#3]
(BTW submitting via pharojs.github.io bug reporting fails)

On Windows, when loading PharoJS "stable" or "bleeding edge" with:
Gofer it smalltalkhubUser: 'noury' project: 'PharoJS'; configurationOf: #PharoJS ; loadBleedingEdge.
The loading process is interrupted with the following error:
"Object as of yet unidentified. "

Source code:
"makeInspect.
	Variable or expression expected -> <javascript: 'var wsd=this;
	return function(){
		wsd._doCallBack_(JSON.stringify({inspect:Object._resultObject_(this)}));
		return this
	}'>"
It seems to me the period after makeinspect is wrong.
After removing it, loading continues successfully.

**Comment by FunctionPoint** [comment]
This seems to be a Windows specific issue.
It does not properly really close the *.js file when it's existence is tested.
I also noticed that the now deprecated class MultiByteFileStream is used.
The debug stack trace from the method PjFileExporter>>writeJavascriptFileNamed: is 22 levels deep (!)
Seems a but overly complex. But that may just be me.
I've tried to add the following code to the start of PjFileExporter>>writeJavascriptFileNamed:
( File named: aFileName ) delete.
But debugging that that freezes Pharo completely on my Windows 10 machine.

**Comment by bouraqadi** [comment]
I've just announced a new version (V18) fixing the test framework stability issues. Al tests are green on Pharo 5 + Mac. Let me know if it works for you. Regarding the code quality. Yes. we have definitely a lot of improvements to do. We do clean ups incrementally. The full middleware including the exporter is on the menu.

**Comment by bouraqadi** [comment]
BTW, you can join the Slack group if you wish. Simply send me you email in a private message.

**Comment by FunctionPoint** [comment]
Can report that "bleedingEdge" is loading fine now on Windows.
Will close this.
