### ISSUE TITLE
Generating index.js files fails on Windows with error "Cannot delete file"

### ISSUE THREAD

**Issue by FunctionPoint** [bouraqadi/PharoJS#4]
I've loaded the latest Pharo 6.1 with bleeding edge PharoJS.
Form the Pharo desktop click "PharoJsPlaygroud" "PjHelloWorldApp" "launch on Pharo".
Now an exception window occurs with the error "Could not delete the old version of file [...\index.js]"
The error occurs in the method PjFileExporter>>createFileNamed: startingWith: and: ifEditableDo: 
The error occurs because the file is already open, probably elsewhere in PharoJS.
A workaround is manually deleting the "index.js" first.
Then the correct index.js file is generated.

**Comment by bouraqadi** [comment]
Do you have the same issue with Pharo 5?

**Comment by FunctionPoint** [comment]
I have the same issue when (f.e.) launching the PjHelloWorldApp from the pre-built Pharo + PharoJS image freshly (just now) downloaded from https://pharojs.github.io.

**Comment by FunctionPoint** [comment]
This kept bugging me, so I made a fix. My first for Pharo ! :)
Wow, Pharo has a lot of classes dealing with files and paths.
The fix is to delete the file early in PjFileExporter>>writeJavascriptFileNamed: ,
before it is opened in testing existence and opening it for writing fails on Windows.
.
Yes, this is kind of a kludge. The real fix would be:
- Use Pharo's non-deprecated file classes for file I/O.
- Don't open the file for reading first, but immediately for writing.
.
Here is the code of the changed method. Line 2 and 3 are added:
.
PjFileExporter>>writeJavascriptFileNamed: aFileName
	"Delete file first, because Windows can't open it for writing later when the file is open."
	aFileName resolve deleteIfAbsent: [ ].
	self
		createFileNamed: aFileName
		startingWith: self headerLine
		and: '// generated by PharoJS'
		ifEditableDo: [ :fileStream | self writeJsCodeOn: fileStream]

**Comment by FunctionPoint** [comment]
PS I've tried to send you a PM for getting added to the Slack group, via your public website.
It there another way I should try?

**Comment by bouraqadi** [comment]
Try a private message on twitter to @pharojs

**Comment by FunctionPoint** [comment]
@bouraqadi implemented the fix, Tnx.
