### ISSUE TITLE
[Pharo 6.1 - Linux/Windows - 64Bits] Javascript Interpreter NOT available

### ISSUE THREAD

**Issue by jeywhat** [bouraqadi/PharoJS#5]
## To reproduce this :

* Obtain a clean Pharo 6.1 image
* Load latest PharoJS:
```
Gofer it
	smalltalkhubUser: 'noury' project: 'PharoJS';
	configurationOf: #PharoJS ;
	loadBleedingEdge.
Open Test Runner
```
* Locate PharoJsBridgeTest > PjBasicTest

* Launch Tests

You will find that most tests will not work because of this bug.
The browser I used is Google Chrome _Version 65.0.3325.181_.

![jsinterpreter](https://user-images.githubusercontent.com/37635074/37832434-dfee8806-2ea8-11e8-9702-0395d65ea9cc.png)

**Comment by bouraqadi** [comment]
PharoJS is currently developed for Pharo 5.

**Comment by bouraqadi** [comment]
Which OS are you using?

**Comment by qCazelles** [comment]
Kubuntu 18.04 64bits with KDE
with Pharo 32bits
