### ISSUE TITLE
Transpiler test bug

### ISSUE THREAD

**Issue by Francodavy** [bouraqadi/PharoJS#6]
1. Obtain Pharo6.1-64  via [https://pharojs.github.io/faq.html](url) 
2. install PharoJs on Pharo  with 
`  Gofer it
  smalltalkhubUser: 'noury' project: 'PharoJS';
  configurationOf: #PharoJS ;
  loadBleedingEdge.`
3. Via Test Runner 
4. Write PharoJS on the top left of the Test runner 
5. Click on  PharoJsTranspiler-Tests 
6. Click PJAstTests 
7. Right click  and select all
8. Run selected

- 2 failures come
     * PjBlockTranspilationTest >>#testBlockWithExternalVariables
       '(function(){return x1})' instead of '(function(x1){return function(){return x1}})(42)'
     * PjBlockTranspilationTest >>#testBlockWithNestedScopes
        '(function(a,x,instVar){return function(v){var w;return [a,v,w,x,y,instVar,123]}})(107,1337,1492)'
         instead of
          '(function(a,x,y,instVar){return function(v){var w;return [a,v,w,x,y,instVar,123]}})     (107,1337,91,1492)'
I don't understand where it comes from .
I am using Pharo6.1-64 on Ubuntu 16.04.

**Comment by bouraqadi** [comment]
PharoJS is currently developed for Pharo 5.
