### ISSUE TITLE
[Pharo 7.0 (Dev Branch) Linux - 64Bits] Install PharoJS

### ISSUE THREAD

**Issue by jeywhat** [bouraqadi/PharoJS#7]
## To reproduce this :
* Obtain a clean Pharo 7.0 image
> wget -O - get.pharo.org/64/70+vm

* Load latest PharoJS:
```
Gofer it
	smalltalkhubUser: 'noury' project: 'PharoJS';
	configurationOf: #PharoJS ;
	loadBleedingEdge.
```

**Problem with extension : ZincHTTPComponents**. It's now existing in Pharo 7 (conflict)
The dependence on ZincHTTPComponents is to be removed.

**Comment by bouraqadi** [comment]
For Pharo 7 and above, we've migrated the code. To install it, please evaluate the following in a playground.
```
Metacello new 
    baseline: 'PharoJS';
    repository: 'github://bouraqadi/PharoJS';
    load
```
