### ISSUE TITLE
[Pharo 6.1 - Windows/Linux - 64 Bits] Tests Communication Faillure

### ISSUE THREAD

**Issue by jeywhat** [bouraqadi/PharoJS#8]
## To reproduce this :

**1**.  Obtain a clean Pharo 6.1 image

**2**.  Load latest PharoJS:
```
Gofer it
	smalltalkhubUser: 'noury' project: 'PharoJS';
	configurationOf: #PharoJS ;
	loadBleedingEdge.
Open Test Runner
```
**3**. Open Test Runner

**4**. Write PharoJS in the search area

**5**. Locate PharoJSCoreLibrariesTest and select all TestCase of this package.

**6**. Click on "Run Selected"

Now you see several web pages open...
At some point, the communication will bug and impact all the other tests.
After, if you click on "Run Errors" you will see that the tests that did not pass, now pass... and crash after some tests. (Repeat this operation if you would see all passes tests)

![communicationfaillure](https://user-images.githubusercontent.com/37635074/37837494-a24135b4-2eb5-11e8-9c1c-874c9c782b5f.png)

**+ memory leak and overload CPU**

![usageproc](https://user-images.githubusercontent.com/37635074/37837488-9f72415c-2eb5-11e8-92a9-3dca05cb6e8a.png)

**In Console :** `WebSocket connection to 'ws://localhost:1133/javascript-bridge' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED`

File Tests Log : 
 * First Run Tests : [tests_Pharo6.1_2018-03-23_15-25-14.txt](https://github.com/bouraqadi/PharoJS/files/1842086/tests_Pharo6.1_2018-03-23_15-25-14.txt)
 * Second Run Tests (Run Errors) : [tests_Pharo6.1_2018-03-23_15-42-07.txt](https://github.com/bouraqadi/PharoJS/files/1842105/tests_Pharo6.1_2018-03-23_15-42-07.txt)
 * Third Run Tests (Run Errors) : [tests_Pharo6.1_2018-03-23_15-42-07-3.txt](https://github.com/bouraqadi/PharoJS/files/1842255/tests_Pharo6.1_2018-03-23_15-42-07-3.txt)

_The browser I used is Google Chrome Version 65.0.3325.181_.

**Comment by bouraqadi** [comment]
PharoJS is developed for Pharo 5
