### ISSUE TITLE
Improve Open Tab in PharoJS Tests Cases

### ISSUE THREAD

**Issue by jeywhat** [bouraqadi/PharoJS#9]
I started testing the PharoCoreLibrariesTest package in the "Test Runner" and it opens a lot of new tabs in my web browser. On some PCs it even crashed.

![tabopen](https://user-images.githubusercontent.com/37635074/37838911-741e3228-2eb9-11e8-9494-7bfb614c411a.png)

The browser I used is Google Chrome Version 65.0.3325.181.

**Comment by bouraqadi** [comment]
This test seem to have been performed on Pharo 6, while PharoJS is currently developed for Pharo 5. Hence the behavior.
